apiVersion: apps/v1
kind: Deployment
metadata:
  name: captureorder
spec:
  selector:
      matchLabels:
        app: captureorder
  replicas: 2
  template:
      metadata:
        labels:
            app: captureorder
      spec:
        containers:
        - name: captureorder
          image: azch/captureorder
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
          - name: MONGOHOST
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongoHost
          - name: MONGOUSER
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongoUser
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: mongosecret
            mountPath: /kvmnt
            readOnly: true
        volumes:
          - name: mongosecret
            flexVolume:
              driver: "azure/kv"
              secretRef:
                name: kvcreds
              options:
                usepodidentity: "false"
                keyvaultname: ie-aks-keyvault
                keyvaultobjectnames: mongo-password # Name of Key Vault secret
                keyvaultobjecttypes: secret
                resourcegroup: ie-azure-k8s
                subscriptionid: 6690b014-bdbd-4496-98ee-f2f255699f70
                tenantid: f8407946-d2c1-4fcc-ae95-63723ace3665

          
          